#  Numpy

In [1]:
# Libraries 

# 1.it is block of code that make programing faster , easier and more powerful
# 2.saves time and make code easier

In [2]:
import numpy as np

In [3]:
# 1. ARRAY

# - container datatype which contain multiple values
# - suports indexing and slicing
# - called as sequence datatype
# - mutable
# - contain homogeneous ele

In [4]:
a = np.array([11,22,33,44,55,67,88,94,72])
a

array([11, 22, 33, 44, 55, 67, 88, 94, 72])

In [5]:
a.shape

# TELLS TOT RWS AND COLUMNS

(9,)

In [6]:
a.ndim

# TELLS DIAMENSION OF GIVEN ARRAY 1D,2D...

1

In [7]:
a.size

# TOT ELE

9

In [8]:
a.dtype

dtype('int64')

In [9]:
# 2D ARRAY

In [10]:
b  = np.array([[1,2,4],[9,8,7]])
b

array([[1, 2, 4],
       [9, 8, 7]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
# 3D ARRAY

In [14]:
c = np.array([[[1,2,3],[4,5,6],[9,8,7]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [9, 8, 7]]])

In [15]:
c.ndim

3

In [16]:
c.shape

# 1... depth 
# 3... rows 
# 3... shows colmns
# respectively.

(1, 3, 3)

In [17]:
c.size

9

In [18]:
# How to convert multi diamensional array into 1d array
# using flatten method

c.flatten()

array([1, 2, 3, 4, 5, 6, 9, 8, 7])

In [19]:
# Create a array by using range

arr = np.arange(1,4)
arr

array([1, 2, 3])

In [20]:
even_arr = np.arange(2,11,2)
even_arr

array([ 2,  4,  6,  8, 10])

In [21]:
table = np.arange(5,51,5)
table

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# CONVERSION OF ROWS INTO ROWS AND COLMNS
# BY USING RESHAPE

x.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
x1 = np.arange(1,101)
x1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
x1.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [27]:
x2 = np.arange(1,101).reshape(2,10,5)
x2

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

# INDEXING

In [28]:
co1 =  np.arange(1,31)
co1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [29]:
co1[[3]]

array([4])

In [30]:
co1[[17]]

array([18])

In [31]:
co = np.arange(1,101).reshape(10,10)
co

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [32]:
co.ndim

2

In [33]:
co[0:4,0:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]])

In [34]:
co[0:5,2:5]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [35]:
co[5:11,7:10]

array([[ 58,  59,  60],
       [ 68,  69,  70],
       [ 78,  79,  80],
       [ 88,  89,  90],
       [ 98,  99, 100]])

# BOOLEAN SLICING AND FILTERING 



In [36]:
co[co>10]

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
co[(co>10) & (co<31)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [38]:
learn = np.arange(1,11)
learn

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# reshape ... chaange diamension
# flaten ... change multidiamensional to 1d

# zeros and ones method

In [40]:
# create 3 array 5 rows 8 colummns  but all element should zero

In [41]:
x = np.zeros((3,5,8))
x

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [42]:
# create 3 array 5 rows 8 colummns  but all element should one

y = np.ones((3,5,8))
y

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

# Transpose

In [43]:
# rows converted to columns
# columns converted to rows

In [44]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
a.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [46]:
a.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# ARITHMATIC OPERATION

In [47]:
x = np.array([10,20,30,40,50])
y = np.array([60,70,80,90,30])

In [48]:
x+y

array([ 70,  90, 110, 130,  80])

In [49]:
x-y

array([-50, -50, -50, -50,  20])

In [50]:
x/y

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 1.66666667])

In [51]:
x*3

array([ 30,  60,  90, 120, 150])

In [52]:
y*2

array([120, 140, 160, 180,  60])

# Broadcasting

In [53]:
p = np.array([10,20,30])
q = np.array([[20,30,40],[10,40,50]])

In [54]:
p+q

array([[30, 50, 70],
       [20, 60, 80]])

In [55]:
p+[10,10,10]

array([20, 30, 40])

In [56]:
q+[10,10,10]

array([[30, 40, 50],
       [20, 50, 60]])

In [57]:
np.power(p,2)

array([100, 400, 900])

In [58]:
np.reciprocal(p)

array([0, 0, 0])

# Statistical operation

In [59]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.max(a,axis=1)

# give maximum val for each column
# 0 for rows
# 1 for column

array([3, 6, 9])

In [61]:
np.max(a)

np.int64(9)

# Argument index

In [62]:
# it is used in deep learning
# it return indices of maximum values along on axis

In [63]:
bob = np.array([[1,2,3],[4,5,6],[7,8,9]])
bob

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.max(a)

np.int64(9)

In [65]:
np.argmax(a)

# index of largest val

np.int64(8)

In [66]:
np.min(a)

np.int64(1)

In [67]:
np.argmin(a)

np.int64(0)

In [68]:
np.sum(a)

np.int64(45)

In [69]:
np.mean(a)

np.float64(5.0)

In [70]:
np.var(a)

np.float64(6.666666666666667)

In [71]:
np.std(a)

np.float64(2.581988897471611)

In [72]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [73]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [74]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [75]:
np.log2(a)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [76]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [77]:
x = np.array([1.33,4.67,93.35])
x

array([ 1.33,  4.67, 93.35])

In [78]:
np.around(x)

array([ 1.,  5., 93.])

In [79]:
np.ceil(x)

array([ 2.,  5., 94.])

In [80]:
np.floor(x)

array([ 1.,  4., 93.])

In [81]:
np.sin(x)

array([ 0.97114838, -0.99910172, -0.78194476])

In [82]:
np.cos(x)

array([ 0.23847605, -0.04237629,  0.62334773])

# Joinig of array

In [83]:
a1 = np.arange(1,17).reshape(4,4)
a2 = np.arange(17,33).reshape(4,4)

In [84]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [85]:
a2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [86]:
a1+a2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [87]:
np.add(a1,a2)

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [88]:
np.concatenate((a1,a2))
# it was row wise addition

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [89]:
# by colmn wise , axis=1

np.concatenate((a1,a2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [90]:
# Methods for concatenation

In [91]:
np.hstack((a1,a2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [92]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [93]:
marks = np.array([20,67,97,57,86,98,46])
print("avg marks",np.mean(marks))
print("max marks",np.max(marks))
print("min marks",np.min(marks))

avg marks 67.28571428571429
max marks 98
min marks 20


# Random number in numpy

In [94]:
# np.random.random()

# 1. for doing random sampling
# 2.returns array of specified shape and fills it with random floats in half open intervals
# 3.give value bet 0 and 1

In [95]:
a= np.random.random((2,3))
a

array([[0.08740449, 0.88488688, 0.7732276 ],
       [0.41438615, 0.55713644, 0.02481037]])

In [96]:
np.random.randint(1,101,(3,3))

array([[55, 79, 49],
       [49, 16, 33],
       [16, 88, 38]], dtype=int32)

In [97]:
np.random.seed(1000)
np.random.randint(1,101)

52

In [98]:
a=[30,40,50,70]
np.random.shuffle(a)
a

[50, 40, 30, 70]

In [99]:
np.random.choice(a)

np.int64(30)